### ISSUE TITLE
Добавить базовые политики отгулов

### ISSUE THREAD

**Issue by ASbeletsky** [ASbeletsky/TimeOffTracker#12]
Система должна поддерживать такие типы отгулов:

- Оплачиваемый отпуск
- Административный (неоплачиваемый) отпуск
- Учебный отпуск
- Больничный

**Оплачиваемый отпуск:**
Ежегодный оплачиваемый отпуск предоставляется за отработанный рабочий год, который отсчитывается со дня прохождения испытательного срока. Всего начисляется 20 рабочих дней отпуска в год. 

**Административный (неоплачиваемый) отпуск:**
Сотрудникам компании разрешается взять не более 15 рабочих дней в год неоплачиваемого отпуска.

**Учебный отпуск:**
Учебный отпуск можно взять только в период сессии, только тем сотрудникам, кто учится на дневном отделении, и проработал уже 6 месяцев с момента прохождения испытательного срока. Суммарное количество дней учебного отпуска не может превышать 10 рабочих дней в год. На одну сессию нельзя взять больше 5 рабочих дней отпуска.

**Больничный:**
При 1-2 днях отсутствия по болезни можно не брать официальный больничный лист. Таких дней может быть не более 7 в год. 
Первые 10 суммарных рабочих дней в году, проведенных на больничном (как по больничному листу, так и без него) компания оплачивает в полном 100% размере.
Следующие 10 суммарных рабочих дней в году, проведенных на больничном (как по больничному листу, так и без него) компания оплачивает в 50% размере.
Следующие 10 суммарных рабочих дней в году, проведенных на больничном (как по больничному листу, так и без него) компания оплачивает в 25% размере. 
Все последующие дни более 30 рабочих дней компания не оплачивает. 

**Необходимо выделить из этого отдельные политики отгулов и добавить их в систему.**

**Comment by Olexseenko** [comment]
Можно использовать Data Seeding в мапинге для инициализации всех необходимых политик. Также предлагаю считать эти политики как дефолтные, поскольку необходимо прикреплять EmployeePositionTimeOffPolicy к политике можно сделать политику дефолтной при значении поля политики как нулл. Данные по типу уменьшения зарплаты от количества больничных можно внести как заметку, и выводить её как предупреждение при попытке подачи заявления или на информационную страницу.

**Comment by Olexseenko** [comment]
Хотя наверное лучше было бы вынести заметку в отдельную таблицу, что бы на неё можно было ссылаться и с определённых политик, и специфицировать в случае чего.

**Comment by Olexseenko** [comment]
"Ежегодный оплачиваемый отпуск предоставляется за отработанный рабочий год, который отсчитывается со дня прохождения испытательного срока. Всего начисляется 20 рабочих дней отпуска в год." Я могу это упростить до начисления 1 января?

**Comment by ASbeletsky** [comment]
@Olexseenko нужно добавлять в Identity дату принятия на работу, и после на него ссылаться
