### ISSUE TITLE
Создание специальных репозиториев и реализация IUnitOfWork

### ISSUE THREAD

**Issue by Olexseenko** [ASbeletsky/TimeOffTracker#16]
Некоторые таблицы нуждаются в корректировке возможностей работы с ними, такими как дополнительные работы при добавлении, изменении или удалении либо отказа к таким действиям в определённых условиях. Так таблицы:
- Таблица EmployeePositionTimeOffPolicy подразумевает не возможность существования 2х и более дефолтных политик или совпадающих по типу и посту в компании.
- Таблица TimeOffPolicyApprovals невозможность одинаковых по посту проверок.
- Таблица TimeOffRequests подразумевает:
-Отсутствие дублирований;
-Проверку на отсутствие пересечений по дням с другими запросами.
- Таблица TimeOffRequestApprovals подразумевает:
-Выставление всем остальным не прошедшим проверкам статус отказа если был получен отказ. И выставления даты решения в таблице TimeOffRequest.
-При выставлении пропуска проверку на оставшиеся проверки в случае отсутствия таковых, выставления даты решения в таблице TimeOffRequest.

**Comment by ASbeletsky** [comment]
@Olexseenko  Хорошо что ты это описал. Только это все должно быть в рамках отдельных задач - как юз кейсов системы. Типа этой https://github.com/ASbeletsky/TimeOffTracker/issues/15. так что создавайте задачи оталкиваясь от фукции системы и там уже прописывайте эти нюансы. Так создадите - можете закрыть эту задачу.
