### ISSUE TITLE
Создание/Редактирование политик отгулов

### ISSUE THREAD

**Issue by Olexseenko** [ASbeletsky/TimeOffTracker#18]
**Use case:**
Администратор создаёт политику отгула.
_When:_ Администратор заходит на страницу политик.
_Then:_ Отображается таблица политик:

- TimeOff Type - тип отгула;
- Employee Position - пост сотрудника которому назначается политика;
- Days per Year - количество дней доступных в год;
- Probation - время в месяцах перед получением первого отпуска отсчитывая от дня принятия на роботу;
- Approvals - содержит список в виде таблицы содержащей столбцы: 
-Amoun - количество проверяющих
-Position - уровень проверяющих
-Main Approver - обязательный проверяющий (ФИО)
- Actions: Edit, Delete, Details

_When:_ Администратор нажимает кнопку Create.
_Then:_ Отображается форма:
TimeOffType: DropDownList
EmployeePosition: DropDownList whith null value to chosen
TimeOffPolicy: DropDownList on selected changing, изменяются данные в таблице просмотра политики отображающей Days per Year и Probation.
Approval: Форма с полями Numeric: Amoun,DropDownList: Position,DropDownList: Main Approver. Но для добавления проверки нужно нажать кнопку добавления которая внесёт выбранное подтверждение в Approvals List, проверив перед этим на отсутствие повторения по позициям.
При создании проводятся проверки на отсутствие существования политик совпадающих по типу и посту.

_When:_ Администратор нажимает кнопку Edit.
_Then:_ Отображается форма как и при Create но уже с заполненными данными.
При нажатии SaveChanges проводиться проверка есть ли запросы на отгул связанные с этой политикой если нет то таблицы просто обновляются в противном случае поле Delited старой политики ставиться в true, и создаётся новая.

_When:_ Администратор нажимает кнопку Delete.
_Then:_ Отображается окно с текстом "Are you sure that you want to delete this requests?" и опциями Yes, No. Если пользователь выбирает Yes, проводиться проверка есть ли запросы на отгул связаные с этой политикой если нет то таблицы просто удаляются, также удаляются все связанные Approvals таблицы в противном случае поле Delited старой политики ставиться в true.

**Comment by ASbeletsky** [comment]
`Main Approver - обязательный проверяющий (ФИО)`
Такого нет, если хоть один не заапрувил - тогда заявка не принимается. Так что убери это

`EmployeePosition: DropDownList whith null value to chosen`
я думаю тут должен быть MultiselectDropDownList не допускающий null

`TimeOffPolicy: DropDownList on selected changing, изменяются данные в таблице просмотра политики отображающей Days per Year и Probation.`
В экране по созданию политики отгулов нужно выбирать плитику отгулов? **Я думаю нужно разделить настройку политик и настройку их подтвержднения для конкретных позиций.** 
Я предлагаю так - когда ты создаешь политику - указываешь имя, тип, и позиции сотрудников, потом указываешь список тех которые должны подтверждать. Тоесть у всех выбраных позиций в рамках политики уже будут назначены апруверы.  _Если для какой-то позиции нужно добавить/убрать аппруверов - на это должна быть отдельная секция или страница_  - **создай на это отдельную задачу**. В рамках этой задачи мы создаем политики с аппруверами по умолчанию. 

`При нажатии SaveChanges проводиться проверка есть ли запросы на отгул связанные с этой политикой если нет то таблицы просто обновляются в противном случае поле Delited старой политики ставиться в true, и создаётся новая.`
Лучше сделай вместе с Delited - IsActive. И нужно еще отлеживать связть между старой и новой политикой, добавить ссылку нужно.

**Comment by Olexseenko** [comment]
Можно создавать при выборе нескольких позиций много дублирующих таблиц? Я имею в виду для каждой позиции свой EmployeePositionTimeOffPolicy, тогда для каждой позиции в случае необходимости можно будет добавить/убрать аппруверов без особых сложностей.
И объединить EmployeePositionTimeOffPolicy c TimeOffPolicy?
![image](https://user-images.githubusercontent.com/40318818/47954298-57238e00-df91-11e8-858c-048a265ba7c5.png)

**Comment by ASbeletsky** [comment]
Как раз в этом и суть - при содании политики для выбраных 4 позиций будет добавлена 1 запись в timeoffpolicy и 4 в EmployeePositionTimeOffPolicy
