### ISSUE TITLE
Создать структуру проекта

### ISSUE THREAD

**Issue by TimurMirzaiev** [ASbeletsky/TimeOffTracker#19]
Создать структуру проекта, выделить слои, добавить ссылки на слои. Добавление пакетов нужных для дальнейшей разработки:

Разбить на слои:
- Utility
- Business
- Data
- Entities
- Dto
- Interfaces
- Web
- Tests

Используемые пакеты:
- Entity Framework
- AutoMapper
- Identity

**Comment by TimurMirzaiev** [comment]
Схема связей

https://drive.google.com/file/d/1KMS0dFIWdEx20gyK_S6yzBIbeak65cU4/view?usp=sharing

**Comment by ASbeletsky** [comment]
Вполне неплохо, единственное лучше переименовать EntityesDTO просто в Dto
