### ISSUE TITLE
Инфраструктура для миграций бд

### ISSUE THREAD

**Issue by Olexseenko** [ASbeletsky/TimeOffTracker#2]
Слой TOT.Data содержащий сущности и контекст, настройки связей в базе с помощью fluent api. Добавление настроек подключения в проект TOT.Web

**Comment by Olexseenko** [comment]
Для миграций в PW:
Add-Migration ИМЯ_МИГРАЦИИ -Project TOT.Data -StartupProject TOT.Web  -  для добавления миграции;
Update-Database -StartupProject TOT.Web  -  для обновления бд по настройкам из appsettings.json
Remove-Migration -Project TOT.Data  -  для удаления последней миграции, если до этого обновить базу по миграции может потребовать очистку базы перед удалением

**Comment by ASbeletsky** [comment]
если задача сделана отписывайте комет и закрывайте
