### ISSUE TITLE
Бизнес логика работы с бд

### ISSUE THREAD

**Issue by Olexseenko** [ASbeletsky/TimeOffTracker#3]
Слой с бизнес логикой работы с бд. Содержит сервисы. Запросы к бд, упаковывание в DTO и обработка ошибок запросов.

**Comment by Akimmax** [comment]
План
Создать проект Dto с необходимыми моделями Net Standart 20
Request_Entities
- TimeOffTypeDTO, RequestStatusDTO, CheckDTO
- TimeOffRequestDTO: TimeOffRequest+поле RequestStatus(RequestStatusDTO)
- Time Off Used Request Item: TimeOffRequest+ ApprovedDate, Totall Time Off,  TimeMeasure
- Time Off Used User Id UserItem: Name,Surname, ListTimeOffRequests, TotallDays, TotallHours
В проект Interfaces добавить интерфейс IMapper 
Добавить репозитории в UnitOfWork
Создать другие необходимые репозитории
Создать проект TOT.Business  Net Standart 20
Добавить в TOT.Business ного папку с Exception для исключений используюшихся в сервисах
Добавить в TOT.Business ного папку с следующими сервисами
Для Request_Entities
- BaseService от которого будут наследоваться остальные
- RequestStatusService: GetAll
- TimeOffTypeService: GetAll
- CheckService: GetAll, Delete Create, Update, GetById, GetAll(UserId)
- TimeOffRequestService: GetAll,  Delete Create, Update, GetById, GetAll(UserId), GetUsedTimeOff byFilter()
Добавить autofac в Web
Зарегистрировать IMapper, UnitOfWork и сервисы в Autofac;
Добавить слой тестов или выделить это в отдельную задачу

**Comment by ASbeletsky** [comment]
@Akimmax 

```
Request_Entities

- TimeOffTypeDTO, RequestStatusDTO, CheckDTO
- TimeOffRequestDTO: поля TimeOffRequest+поле RequestStatus(RequestStatusDTO)
- UsedTimeOffRequest: поля TimeOffRequest+ DateOfApprove, DateOfRequest, TotallTimeOff, TimeMeasure(TimeMeasuresDTO)
- UsedTimeOffRequestUser: Name,Surname, Requests( List UsedTimeOffRequest), TotallDaysOff, TotallHoursOff
```
 Пока добавлять Request_Entities Dto не нужно. Когда будут задачи где будет UI, в рамках их будут дабавлены все необходимые dto. 

```

- RequestStatusService: GetAll
- TimeOffTypeService: GetAll
- CheckService: GetAll, Delete Create, Update, GetById, GetAll(UserId)
- TimeOffRequestService: GetAll, Delete Create, Update, GetById, GetAll(UserId), GetUsedTimeOff byFilter()

```
Это тоже пока не нужно
