### ISSUE TITLE
Деплой

### ISSUE THREAD

**Issue by Akimmax** [ASbeletsky/TimeOffTracker#4]
1.Развернуть приложение на удаленный хостинг;
2.Деплой Бызы Данных
3.По возможности, добавить интеграцию с github

**Comment by Akimmax** [comment]
Мой студенческий акк на азур уже тоже не работоспособный, поэтому больше нет возможности его использовать для реализации задачи.
Варианты решения:
1.Позавчера завел бесплатный акк азур (он вроде бесплатный пока сам не перейдешь на платный). Вчера проверил, можно пока туда задеплоить (правда только на 30 дней)
2.Использовать другой хостинг для развертывания, но все найденные с Core требуют подписки с первого месяца, к примеру (Parking.ru, Infobox, Smarterasp.net).
3.Для БД использовать https://www.freemysqlhosting.net/ или https://www.db4free.net/
4.Возможно вы предложите что-то рациональнее

**Comment by Akimmax** [comment]
В качестве БД использую бесплатный аккаунт. https://www.db4free.net/.
Данные для подключения:
"DefaultConnection": "server=db4free.net;UserId=totadmin;Password=Password0;database=totaprioritdb;"

**Comment by Akimmax** [comment]
В LMS Web можно попасть по ссылке
https://tot-apriorit.azurewebsites.net

**Comment by Akimmax** [comment]
Добавлена интеграция с github

**Comment by ASbeletsky** [comment]
если задача сделана отписывайте комет и закрывайте
