### ISSUE TITLE
Создание сущностей и их мапинг

### ISSUE THREAD

**Issue by Olexseenko** [ASbeletsky/TimeOffTracker#8]
Создание Entities и их настройка через Fluent API

**Comment by Olexseenko** [comment]
По сути база делиться на две части запрос на отгул и политика компании по выдачи отгулов. С общей таблицей TimeOffTypes, которая содержит всего 2 поля Id и Title (текстовое название типа).
Часть которая отвечает за запрос и его обработку состоит из:
- TimeOffRequsts таблица в которой содержаться сами запросы, имеет ссылки на тип отгула и работника который претендует на отгул, также дату начала отгула и конца, поле дополнительной информации.
-Checks таблица проверок которые должен пройти запрос перед его подтверждением. Сохраняет дату принятия решения, ссылку на работника обрабатывающего заявление, статус (принято на обработку, обрабатывается, отказано, принято), причину отказа.
-RequstStatuses хранит список состояний проверки (принято на обработку, обрабатывается, отказано, принято).
Часть которая отвечает за политику компании:
-Positions звания внутри компании;
-TimeOffPolicies правила получения определённого типа отгула для определённого поста. Включает тип отгула, пост, список людей которые должны подтвердить запрос и правила начисления.
-TimeOffPoliciesCheckers список людей которые должны подтвердить запрос.
-Accrualschedules схема начислений часов. Включает в себя количество времени перед началом работы схемы, количество начисляемых часов и список дат когда эти часы обновляются.
-TimeMeasures форматы времени по типу часы, дни, месяца и года.
![default](https://user-images.githubusercontent.com/40318818/47232349-1d228b80-d3d8-11e8-9e5c-60897fc4cad0.png)

**Comment by ASbeletsky** [comment]
Что означает поле Amount в таблице TimeOffPoliciesCheckers?

> Checks таблица проверок которые должен пройти запрос перед его подтверждением.
Лучше назови TimeOffRequestApproval

> RequstStatuses хранит список состояний проверки
Лучше назови TimeOffRequestApprovalStatuses

> Positions звания внутри компании
Лучше назови EmployeePosition

> TimeOffPolicies правила получения определённого типа отгула для определённого поста.
Получается что как раз в этой таблице хранится не сама политика отгула, а именно то, как она соотносится с конкретным постом (EmployeePosition). Значит должна быть таблица с политиками (TimeOffPolicy) и на нее будет ссылаться эта таблица, можно ее назвать как EmployeePositionTimeOffPolicy.

> Accrualschedules схема начислений часов.
Как раз это больше всего похоже на саму политику (TimeOffPolicy)

> Включает в себя количество времени перед началом работы схемы
Зачем это нужно?

> количество начисляемых часов и список дат когда эти часы обновляются.
Я думаю будет достаточно хранить количество доступных дней отгула за год

Для начала остановимся на этом, потом может усложним.

**Comment by Olexseenko** [comment]
![image](https://user-images.githubusercontent.com/40318818/47569767-244c1b00-d93d-11e8-8e49-32303383e8a6.png)

**Comment by Olexseenko** [comment]
Переименованы таблицы:

- Checks >> TimeOffRequestapprovals
- RequestStatuses >> TimeOffRequestApprovalStatuses (Было убрано AI)
- Positions (сущность была переименована на EmployeePositions)
- TimeOffPolicy >> EmployeePositionTimeOffPolicies (Список ссылок на политики заменён на 1 к 1)
- TimeOffPoliciesCheckers >> TimeOffPolicyApprovals ( Amount - количество проверяющих одного уровня для запроса.
UserId - человек который должен проверять каждый запрос определённого типа.)
- TimeOffTipe (убран AI)
- Accrualschedules >> TimeOffPolicy (ResetDate - дата обновления обновления дней отгулов, нужна для отсутствия зависимостей от даты принятия на роботу.
TimeOffDayPerYear - дней отгула в год.)
