### ISSUE TITLE
Excel data import

### ISSUE THREAD

**Issue by mishavetl** [ASbeletsky/TimeOffTracker#82]
## Overview

The system is a replacement for excel-based vacation management. So previous data is stored in Excel.
The current implementation does not support Excel data import.

## Requirements

* Data import is being done by the following steps.
  1. File attachment.
  2. Sheets selection.
  3. Data ranges selection.

## Implementation guidelines

* As an option, data ranges selection can be implemented by column name/title selection.
* [https://github.com/tonyqus/npoi](https://github.com/tonyqus/npoi) should be used for server-side Excel parsing.

Estimate: 35 hours
Deadline: 21.04.2020

**Comment by mishavetl** [comment]
I think that we need to somehow take into account weekends because they are not counted as vacation days, however, a vacation can include weekends.

**Comment by mishavetl** [comment]
For instance, the following should be a single paid vacation with 6 vacation days.

![image](https://user-images.githubusercontent.com/9119326/77214440-e0504c00-6b17-11ea-9b24-976bffdad0af.png)

**Comment by vitderkach** [comment]
I've taken into account it, but another way. The start of vacation request should be start from vacation day, not holiday. It's quite silly to count the vacation from holidays, because they aren't considered as vacation days finally.
